import PDFDocument from 'pdfkit';

export function generateOrderPdf({ order, customerName, customerEmail }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).font('Helvetica-Bold').text('INTEGRATION', { continued: false });
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#666666').text('Different Styles, One Identity');
    doc.moveDown(1);

    doc.fontSize(16).font('Helvetica-Bold').fillColor('#000000').text('Order Receipt');
    doc.moveDown(0.5);

    doc.fontSize(10).font('Helvetica');
    doc.text(`Order ID:    ${order._id}`);
    doc.text(`Date:        ${new Date(order.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
    doc.text(`Status:      ${order.status.replace(/_/g, ' ').toUpperCase()}`);
    doc.text(`Payment:     ${order.paymentMethod.toUpperCase()}`);
    doc.moveDown(1);

    doc.fontSize(12).font('Helvetica-Bold').text('Customer');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica');
    doc.text(`Name:    ${customerName}`);
    doc.text(`Email:   ${customerEmail}`);
    doc.text(`Phone:   ${order.contactPhone}`);
    doc.text(`Address: ${order.deliveryAddress}`);
    doc.moveDown(1);

    doc.fontSize(12).font('Helvetica-Bold').text('Items');
    doc.moveDown(0.3);

    const tableTop = doc.y;
    const colWidths = { title: 200, size: 60, qty: 50, price: 80, total: 80 };
    const startX = 50;

    doc.fontSize(9).font('Helvetica-Bold');
    doc.text('ITEM', startX, tableTop, { width: colWidths.title });
    doc.text('SIZE', startX + colWidths.title, tableTop, { width: colWidths.size });
    doc.text('QTY', startX + colWidths.title + colWidths.size, tableTop, { width: colWidths.qty });
    doc.text('PRICE', startX + colWidths.title + colWidths.size + colWidths.qty, tableTop, { width: colWidths.price });
    doc.text('TOTAL', startX + colWidths.title + colWidths.size + colWidths.qty + colWidths.price, tableTop, { width: colWidths.total });

    doc.moveTo(startX, tableTop + 15).lineTo(545, tableTop + 15).stroke('#cccccc');

    let y = tableTop + 25;
    doc.font('Helvetica').fontSize(10);

    for (const item of order.items) {
      const lineTotal = item.priceAtOrder * item.quantity;
      doc.text(item.title, startX, y, { width: colWidths.title });
      doc.text(item.size, startX + colWidths.title, y, { width: colWidths.size });
      doc.text(String(item.quantity), startX + colWidths.title + colWidths.size, y, { width: colWidths.qty });
      doc.text(`৳${(item.priceAtOrder / 100).toLocaleString()}`, startX + colWidths.title + colWidths.size + colWidths.qty, y, { width: colWidths.price });
      doc.text(`৳${(lineTotal / 100).toLocaleString()}`, startX + colWidths.title + colWidths.size + colWidths.qty + colWidths.price, y, { width: colWidths.total });
      y += 20;
    }

    doc.moveTo(startX, y).lineTo(545, y).stroke('#cccccc');
    y += 10;

    doc.font('Helvetica-Bold').fontSize(12);
    doc.text('TOTAL', startX + colWidths.title + colWidths.size + colWidths.qty, y, { width: colWidths.price, align: 'right' });
    doc.text(`৳${(order.totalAmount / 100).toLocaleString()}`, startX + colWidths.title + colWidths.size + colWidths.qty + colWidths.price, y, { width: colWidths.total });

    y += 30;
    doc.fontSize(9).font('Helvetica').fillColor('#666666');
    doc.text('Payment is manual via bKash. Customer will be contacted to arrange payment.', startX, y);
    doc.moveDown(2);
    doc.text('Generated by Integration — Different Styles, One Identity.', startX, doc.y, { align: 'center' });

    doc.end();
  });
}
